### ISSUE TITLE
Code to force user to wait 15 sec before login (till upload all apis)

### ISSUE THREAD

**Issue by mo7amedehab97** [GSG-FC03/Cosmetics-Store#28]
relates #8 
_TASKS_

- [x] #29
- [x] #31
![Screenshot 2021-08-05 at 20-43-49 Document](https://user-images.githubusercontent.com/61945138/128396684-377cb2c9-5240-4c9d-8305-67c45b5850a4.png)

**Comment by MMansour87** [comment]
Completed
