### ISSUE TITLE
Rose Cosmetics user journey

### ISSUE THREAD

**Issue by EmanHass** [GSG-FC03/Cosmetics-Store#7]
As a customer, I can be able to browse all products that the app provide, know details about product I select it, able to add products in the cart then pay online.

- [x] #8 
- [x] #9 
- [x] #13
- [x] #14 
- [x] #15 
- [x] #16 
- [x] #17 
- [x] #18 
- [x] #19

**Comment by MMansour87** [comment]
Completed
