### ISSUE TITLE
User Stroy1: As a Customer, I can Login using my name so that I find my saved products in the cart.

### ISSUE THREAD

**Issue by EmanHass** [GSG-FC03/Cosmetics-Store#8]
Relates #7
  
####Tasks
- [x] #24
- [x] #26
- [x] #25
- [x] #28

![Welcome Page](https://user-images.githubusercontent.com/79720467/128326609-c069b07b-c197-4b23-8059-22095ac2490f.png)

**Comment by MMansour87** [comment]
Completed
