### ISSUE TITLE
User Story2: As a Customer, I can Explore & Search All products in App and Explore recommended products so that I may reach a good recommended product.

### ISSUE THREAD

**Issue by EmanHass** [GSG-FC03/Cosmetics-Store#9]
Relates #7 
_**Objective:**_ Create mainPage to browse all products.

**_Tasks_**
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #52
- [x] #100

![Main Page](https://user-images.githubusercontent.com/79720467/128595573-576a2734-d39f-4edb-952d-72d8aee6fb7e.jpg)

![image](https://user-images.githubusercontent.com/83221547/128605041-6c36e80b-8969-4ad5-9739-643dcf00f70c.png)

**Comment by MMansour87** [comment]
Completed
